import { Suspense } from "react";
import "./globals.css";
import LoadingPage from "./loading";
import Wrapper from "./Wrapper";


export const metadata = {
  title: "LuxuryVerse",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="montserrat-font">
          <Wrapper>
          {children}
          </Wrapper>
      </body>
    </html>
  );
}